### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by anaschaudhary33** [hemantapkh/TorrentHunt#38]
I am getting the the following error
```
 pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 3135 seconds is required (caused by "auth.ImportBotAuthorization")
```

**Comment by 0xWebMilk** [comment]
This error is due to the fact that you are sending too many requests to the server. Just wait for some time, usually the timeout is specified in the error.
